export const CardsItem = [{
        img: "https://i.postimg.cc/NMznRgmB/Todo-List1.jpg",
        title: 'Todo List with PHP',
        description: 'This project is a todo list made in php using ajax technology and the sweetalert library to make it a bit more user friendly.',
        urlButton: 'https://github.com/LuisEstebanC/TodoListPHP',
        imageAlt: 'Todo List Image',
        Style: 'square',
        buttonContent: 'View source code',
    },
    {
        img: 'https://i.postimg.cc/3xPm0NL3/Organic-Care.jpg',
        title: 'Web layout',
        description: 'This is the layout of a project, made in React js, it also has a login function, a register made in ASP.NET core with SQL-Server as database, for confidentiality this repo only has the layout with some functions.',
        urlButton: 'https://github.com/LuisEstebanC/OrganicCare',
        imageAlt: 'web Proyect',
        Style: 'square',
        buttonContent: 'View source code',
    },
    {
        img: 'https://i.postimg.cc/XJMy8qS8/E-comerce9.jpg',
        title: 'e-commerce',
        description: 'This ecommerce was a project in which I was in charge of the frontend of the page, I made the frontend of the page following the design of a mockup.',
        urlButton: 'https://github.com/LuisEstebanC/PF3',
        Style: 'square',
        buttonContent: 'View source code',
    },
]